<?php
// $Id$
//Created using Brandon Dixon's <brandon.s.dixon@gmail.com> Skeleton Module Generator
/**
* Replace all comments if you would like. Be sure to identify params, files and returns in your comments
*/

// From http://drupal.org/node/617694

/**
 * Implementation of hook_elements().
 *
 * This extends optionwidgets_elements() to add in additional processing.
 * Note that your module must be weighted higher than optionwidgets
 * for this code to take effect.
 */
function thurgood_custom_module_elements() {
  $type['optionwidgets_buttons']['#process'][] = 'remove_radio_na';
  return $type;
}

/**
 * Unset the N/A option on option widget radio buttons.
 */
function remove_radio_na($element) {
  unset($element['value']['#options']['']);
  return $element;
}

/**
  * Implementation of hook_block. 
  */
function thurgood_custom_module_block($op = 'list', $delta = '', $edit = array()) {

  define("ICONPATH", "profiles/thurgood/themes/sky_thurgood/images/Coquette/");

  switch ($op) {

    case 'list':
      $blocks['article'] = array('info' => t('Thurgood: Dashboard Article Block'));
      $blocks['event'] = array('info' => t('Thurgood: Dashboard Event Block'));
      $blocks['place'] = array('info' => t('Thurgood: Dashboard Place Block'));

      $blocks['tutorial'] = array('info' => t('Thurgood: Dashboard Tutorial Block'));

      $blocks['filter'] = array('info' => t('Thurgood: Dashboard Filter Block'));
      $blocks['workflow'] = array('info' => t('Thurgood: Dashboard Workflow Block'));

      $blocks['main'] = array('info' => t('Thurgood: Dashboard Main Block'));
      $blocks['userinfo'] = array('info' => t('Thurgood: Dashboard User Info Block'));
      return $blocks;

    // In case we eventually want to add config options here.
    case 'configure':
      $form = array();
      return $form;

    case 'save':
      return;

    case 'view':

      $type = node_get_types('type', $delta);

      switch ($delta) {
        case 'article':

          $block['content'] = l('<h3 class="dashboard-block">' . t('Write an Article') . '</h3>' . theme_image(ICONPATH . 'Coquette_3/png/128x128/text_page.png', 'Write an Article') . '<p class="dashboard-block">' . $type->description . '</p>',
                                'node/add/article',
                                array('html' => TRUE));
          break;

        case 'event':
          $block['content'] = l('<h3 class="dashboard-block">' . t('Create an Event') . '</h3>' . theme_image(ICONPATH . 'Coquette_3/png/128x128/calendar.png', 'Create an Event') . '<p class="dashboard-block">' . $type->description . '</p>',
                                'node/add/event',
                                array('html' => TRUE));
          break;

        case 'place':
          $block['content'] = l('<h3 class="dashboard-block">' . t('List a Place') . '</h3>' . theme_image(ICONPATH . 'Coquette_1/png/128x128/globe.png', 'List a Place') . '<p class="dashboard-block">' . $type->description . '</p>',
                                'node/add/place',
                                array('html' => TRUE));
          break;

        case 'tutorial':
          $block['content'] = l('<h3 class="dashboard-block">' . t('View Tutorial') . '</h3>' . theme_image(ICONPATH . 'Coquette_3/png/128x128/help.png', 'View Tutorial') . '<p class="dashboard-block">Learn how the ctreentry.info website works here.'</p>',
                                'tutorial',
                                array('html' => TRUE));
          break;

        case 'filter':
          $block['content'] = l('<h3 class="dashboard-block">' . t('Filter Content') . '</h3>' . theme_image(ICONPATH . 'Coquette_3/png/128x128/search_page.png', 'Filter Content') . '<p class="dashboard-block">View the site's content and apply filters to narrow down your search.</p>',
                                'admin/content/filter',
                                array('html' => TRUE));
          break;

        case 'workflow':
          $block['content'] = l('<h3 class="dashboard-block">' . t('Monitor Workflow') . '</h3>' . theme_image(ICONPATH . 'Coquette_3/png/128x128/page_process.png', 'Monitor Workflow') . '<p class="dashboard-block">View the publishing status of content across the site.</p>',
                                'workflow',
                                array('html' => TRUE));
          break;

        case 'main':
          $block['content'] = t('Have a bunch of links here that are the main body.');
          break;

        case 'userinfo':
          $block['subject'] = t('My Info');
          $block['content'] = t('Some user info and tokens and such go in here.');
          break;

      }
      return $block;
  }
}

/**
 * A filler block content function.
 */
function thurgood_custom_module_contents($which_block) {
  switch ($which_block) {
    case 1:
      // Modules would typically perform some database queries to fetch the
      // content for their blocks. Here, we'll just use the variable set in the
      // block configuration or, if none has set, a default value.
      return variable_get('thurgood_custom_module_string',  t('A default value.'));

    case 2:
      // It is possible that your block will not have any content, since it is
      // probably dynamically constructed. In this case, Drupal will not display
      // the block at all.
      return;
  }
}
